/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViniRouteImport } from './routes/vini'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DrinkRouteImport } from './routes/drink'
import { Route as IndexRouteImport } from './routes/index'

const ViniRoute = ViniRouteImport.update({
  id: '/vini',
  path: '/vini',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkRoute = DrinkRouteImport.update({
  id: '/drink',
  path: '/drink',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drink': typeof DrinkRoute
  '/menu': typeof MenuRoute
  '/vini': typeof ViniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drink' | '/menu' | '/vini'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drink' | '/menu' | '/vini'
  id: '__root__' | '/' | '/drink' | '/menu' | '/vini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrinkRoute: typeof DrinkRoute
  MenuRoute: typeof MenuRoute
  ViniRoute: typeof ViniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vini': {
      id: '/vini'
      path: '/vini'
      fullPath: '/vini'
      preLoaderRoute: typeof ViniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink': {
      id: '/drink'
      path: '/drink'
      fullPath: '/drink'
      preLoaderRoute: typeof DrinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrinkRoute: DrinkRoute,
  MenuRoute: MenuRoute,
  ViniRoute: ViniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
